export const employee = [
  {
    name: "John Doe",
    gender: "Male",
    materialStatus: "Married",
    dob: "12/08/1989",
    dependents: "1",
    address: "Waigani Drive 123, Port Moresby, N.C.D",
  },
];

export const employer = [
  {
    name: "Brian Bell",
    date: "21/06/2022",
    position: "Sales Rep",
    department: "Marketing",
    address: "Boroko",
    staffId: "01234",
    payOfficer: "Jack Daniels",
    phoneNumber: "2356876",
    mobileNumber: "78558885",
    email: "john@email.com",
    fileUrl: "#",
  },
];

export const bank = [
  {
    bank: "BSP",
    branch: "Waigani",
    accountType: "Savings",
    account: 1258586382,
    accountName: "John Doe",
  },
];

export const loan = [
  {
    invoice: 123456,
    amount: 5000,
    repayment: 200,
    term: 26,
    purpose: "Budget booster for the Christmas celebrations",
  },
];

export const fakeUsers = [
  {
    id: 55,
    userName: "BBAdmin",
    userPassword:
      "$2a$10$ES8sD3RPtZSbjAF7O92tBObhLTdJJUvMQRnVn0DbgKAo2LlFYhJEy",
    userRole: 0,
    branch: "Port Moresby",
    lastLoginDate: "2021-05-11T04:59:05.000Z",
    dateCreated: "2021-05-11T04:59:05.000Z",
    pwdUpdate: "2021-05-11T04:59:05.000Z",
    businessUser: "Brianbell",
    deleted: 0,
  },
  {
    id: 56,
    userName: "BBStaff",
    userPassword:
      "$2y$10$nxWfEpTGTV/qLzXWFM/csOzDjy562A2KBnKzQwAkIfAneqDHLPS3W",
    userRole: 1,
    branch: "Port Moresby",
    lastLoginDate: "2021-05-11T05:13:26.000Z",
    dateCreated: "2021-05-11T05:13:26.000Z",
    pwdUpdate: "2021-05-11T05:13:26.000Z",
    businessUser: "Brianbell",
    deleted: 0,
  },
  {
    id: 58,
    userName: "OSGStaff",
    userPassword:
      "$2y$12$JXcntRePS8tCUbmLG83zGu8mP9Y9GI7uSbeZCYQh1VDeFRpDVY8Gi",
    userRole: 3,
    branch: "Port Moresby",
    lastLoginDate: "2021-05-11T05:17:59.000Z",
    dateCreated: "2021-05-11T05:17:59.000Z",
    pwdUpdate: "2021-05-11T05:17:59.000Z",
    businessUser: "FinCorp",
    deleted: 0,
  },
  {
    id: 59,
    userName: "BBCust",
    userPassword:
      "$2y$10$nxWfEpTGTV/qLzXWFM/csOzDjy562A2KBnKzQwAkIfAneqDHLPS3W",
    userRole: 2,
    branch: "Port Moresby",
    lastLoginDate: "2021-05-11T05:19:03.000Z",
    dateCreated: "2021-05-11T05:19:03.000Z",
    pwdUpdate: "2021-05-11T05:19:03.000Z",
    businessUser: "Brianbell",
    deleted: 0,
  },
  {
    id: 60,
    userName: "testuser",
    userPassword:
      "$2y$10$nxWfEpTGTV/qLzXWFM/csOzDjy562A2KBnKzQwAkIfAneqDHLPS3W",
    userRole: 0,
    branch: "Port Moresby",
    lastLoginDate: "2021-06-08T22:05:20.000Z",
    dateCreated: "2021-06-08T22:05:20.000Z",
    pwdUpdate: "2021-06-08T22:05:20.000Z",
    businessUser: "Brianbell",
    deleted: 1,
  },
  {
    id: 61,
    userName: "Test",
    userPassword:
      "$2y$10$vDR0GvuKNPITFxjNp3PIRueU4kr70GVjxGns7AJvHab1afKaaE38W",
    userRole: 2,
    branch: "Madang",
    lastLoginDate: "2022-06-14T05:47:23.000Z",
    dateCreated: "2022-06-14T05:47:23.000Z",
    pwdUpdate: "2022-06-14T05:47:23.000Z",
    businessUser: "Brianbell",
    deleted: 0,
  },
  {
    id: 62,
    userName: "gdorke",
    userPassword:
      "$2a$10$OJvptOm/pdYZjkPE.AlwcuZZteeoFi9XCiQzpDOT3NGsll8/1COpa",
    userRole: 2,
    branch: "Port Moresby",
    lastLoginDate: "2022-10-12T02:33:42.000Z",
    dateCreated: "2022-10-12T02:33:42.000Z",
    pwdUpdate: "2022-10-12T02:33:42.000Z",
    businessUser: "FinCorp",
    deleted: 0,
  },
  {
    id: 63,
    userName: "jangap",
    userPassword:
      "$2a$10$OJvptOm/pdYZjkPE.AlwcuZZteeoFi9XCiQzpDOT3NGsll8/1COpa",
    userRole: 2,
    branch: "Port Moresby",
    lastLoginDate: "2022-10-12T02:42:14.000Z",
    dateCreated: "2022-10-12T02:42:14.000Z",
    pwdUpdate: "2022-10-12T02:42:14.000Z",
    businessUser: "FinCorp",
    deleted: 0,
  },
  {
    id: 67,
    userName: "dkalua",
    userPassword:
      "$2a$10$OJvptOm/pdYZjkPE.AlwcuZZteeoFi9XCiQzpDOT3NGsll8/1COpa",
    userRole: 2,
    branch: "Port Moresby",
    lastLoginDate: "2022-10-14T00:31:56.000Z",
    dateCreated: "2022-10-14T00:31:56.000Z",
    pwdUpdate: "2022-10-14T00:31:56.000Z",
    businessUser: "FinCorp",
    deleted: 0,
  },
  {
    id: 68,
    userName: "Olivia Iannes",
    userPassword:
      "$2a$10$OJvptOm/pdYZjkPE.AlwcuZZteeoFi9XCiQzpDOT3NGsll8/1COpa",
    userRole: 2,
    branch: "Port Moresby",
    lastLoginDate: "2022-10-18T05:21:14.000Z",
    dateCreated: "2022-10-18T05:21:14.000Z",
    pwdUpdate: "2022-10-18T05:21:14.000Z",
    businessUser: "Brian Bell",
    deleted: 0,
  },
];

export const clientsFake = [
  {
    id: 1,
    lastName: "Snow",
    firstName: "Jon",
    email: "jon@gmail.com35",
    status: "Active",
    roleId: "Client",
    partnerId: "Brian Bell",
  },
  {
    id: 2,
    lastName: "Lannister",
    firstName: "Cersei",
    email: "jon@gmail.com42",
    status: "Disable",
    roleId: "Client",
    partnerId: "Brian Bell",
  },
  {
    id: 3,
    lastName: "Lannister",
    firstName: "Jaime",
    email: "jon@gmail.com45",
    status: "Active",
    roleId: "Client",
    partnerId: "Brian Bell",
  },
  {
    id: 4,
    lastName: "Stark",
    firstName: "Arya",
    email: "jon@gmail.com16",
    status: "Disable",
    roleId: "Client",
    partnerId: "Brian Bell",
  },
  {
    id: 5,
    lastName: "Targaryen",
    firstName: "Daenerys",
    email: "jon@gmail.comnu",
    status: "Active",
    roleId: "Client",
    partnerId: "Brian Bell",
  },
  {
    id: 6,
    lastName: "Melisandre",
    firstName: null,
    email: "jon@gmail.com15",
    status: "Disable",
    roleId: "Client",
    partnerId: "Brian Bell",
  },
];

export const fakeApplications = [
  {
    customerId: 104,
    salesRep: "pjackson",
    appId: 302,
    firstName: "Gedare",
    lastName: "Dorke",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "male",
    maritalStatus: "married",
    dependents: 1,
    profilePicture: null,
    addressId: 104,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 3232323,
    customerMobile: 3232323,
    customerEmail: "ggedare@mail.com.pg",
    customerAddress: "P.O Box 123",
    bankId: 131,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Gedare Dorke",
    accNumber: 12345678,
    loanId: 99,
    invoiceNumber: "12345678",
    purpose: "Hire Purchase",
    amount: 500,
    repaymentAmount: 33,
    term: 25,
    employerId: 100,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "gdorke@mail.com.pg",
    fileNumber: "10064",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay.zip",
    rawFileName: null,
    status: "Approved",
  },
  {
    customerId: 105,
    salesRep: "pjackson",
    appId: 303,
    firstName: "Duncan",
    lastName: "Petrus",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "male",
    maritalStatus: "single",
    dependents: 0,
    profilePicture: null,
    addressId: 105,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 3232323,
    customerMobile: 3232323,
    customerEmail: "ggedare@mail.com.pg",
    customerAddress: "P.O Box 123",
    bankId: 132,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Gedare Dorke",
    accNumber: 12345678,
    loanId: 100,
    invoiceNumber: "12345678",
    purpose: "Hire Purchase",
    amount: 500,
    repaymentAmount: 34,
    term: 25,
    employerId: 101,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "gdorke@mail.com.pg",
    fileNumber: "10064",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay1.zip",
    rawFileName: null,
    status: "Pending",
  },
  {
    customerId: 106,
    salesRep: "pjackson",
    appId: 304,
    firstName: "Augustina",
    lastName: "Allan",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "female",
    maritalStatus: "married",
    dependents: 0,
    profilePicture: null,
    addressId: 106,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 3232323,
    customerMobile: 3232323,
    customerEmail: "ggedare@mail.com.pg",
    customerAddress: "P.O Box 123",
    bankId: 133,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Gedare Dorke",
    accNumber: 12345678,
    loanId: 101,
    invoiceNumber: "12345678",
    purpose: "Hire Purchase",
    amount: 500,
    repaymentAmount: 50,
    term: 25,
    employerId: 102,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "gdorke@mail.com.pg",
    fileNumber: "10069",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay2.zip",
    rawFileName: null,
    status: "Approved",
  },
  {
    customerId: 108,
    salesRep: "pjackson",
    appId: 306,
    firstName: "Peter",
    lastName: "Totono",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "male",
    maritalStatus: "single",
    dependents: 1,
    profilePicture: null,
    addressId: 108,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 3232323,
    customerMobile: 3232323,
    customerEmail: "ptotono@mail.com",
    customerAddress: "P.O Box 123",
    bankId: 134,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Gedare Dorke",
    accNumber: 12345678,
    loanId: 102,
    invoiceNumber: "12345678",
    purpose: "Hire Purchase",
    amount: 5000,
    repaymentAmount: 250,
    term: 52,
    employerId: 104,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "ptotono@mail.com",
    fileNumber: "10070",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay4.zip",
    rawFileName: null,
    status: "Pending",
  },
  {
    customerId: 109,
    salesRep: "pjackson",
    appId: 307,
    firstName: "Peniel",
    lastName: "Kalamin",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "male",
    maritalStatus: "single",
    dependents: 1,
    profilePicture: null,
    addressId: 109,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 3232323,
    customerMobile: 3232323,
    customerEmail: "pkalamin@mail.com",
    customerAddress: "P.O Box 123",
    bankId: 135,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Gedare Dorke",
    accNumber: 12345678,
    loanId: 103,
    invoiceNumber: "12345678",
    purpose: "Hire Purchase",
    amount: 600,
    repaymentAmount: 61,
    term: 26,
    employerId: 105,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "pkalamin@mail.com",
    fileNumber: "10071",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay5.zip",
    rawFileName: null,
    status: "Approved",
  },
  {
    customerId: 110,
    salesRep: "pjackson",
    appId: 308,
    firstName: "Duncan",
    lastName: "Allan",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "male",
    maritalStatus: "single",
    dependents: 0,
    profilePicture: null,
    addressId: 110,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 3232323,
    customerMobile: 3232323,
    customerEmail: "dallan@mail.com",
    customerAddress: "P.O Box 123",
    bankId: 136,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Duncan Allan",
    accNumber: 98765430,
    loanId: 104,
    invoiceNumber: "12345678",
    purpose: "Hire Purchase",
    amount: 500,
    repaymentAmount: 60,
    term: 102,
    employerId: 106,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "dallan@mail.com",
    fileNumber: "10089",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay6.zip",
    rawFileName: null,
    status: "Declined",
  },
  {
    customerId: 111,
    salesRep: "pjackson",
    appId: 309,
    firstName: "Kimbarely",
    lastName: "Kilo",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "female",
    maritalStatus: "single",
    dependents: 1,
    profilePicture: null,
    addressId: 111,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 323323,
    customerMobile: 3232323,
    customerEmail: "kkilo@mail.com.pg",
    customerAddress: "P.O Box 123",
    bankId: 137,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Kimbarely Kilo",
    accNumber: 2147483647,
    loanId: 105,
    invoiceNumber: "12345678",
    purpose: "Hire Purchase",
    amount: 10000,
    repaymentAmount: 250,
    term: 109,
    employerId: 107,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "kkilo@mail.com.pg",
    fileNumber: "100090",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay7.zip",
    rawFileName: null,
    status: "Approved",
  },
  {
    customerId: 112,
    salesRep: "pjackson",
    appId: 310,
    firstName: "Simon",
    lastName: "Jones",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "male",
    maritalStatus: "single",
    dependents: 0,
    profilePicture: null,
    addressId: 112,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 3232323,
    customerMobile: 3232323,
    customerEmail: "sjones@mail.com",
    customerAddress: "P.O Box 123",
    bankId: 138,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Simon Jones",
    accNumber: 12345678,
    loanId: 106,
    invoiceNumber: "12345678",
    purpose: "White goods purchase",
    amount: 500,
    repaymentAmount: 150,
    term: 52,
    employerId: 108,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "sjones@mail.com",
    fileNumber: "100100",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay8.zip",
    rawFileName: null,
    status: "Approved",
  },
  {
    customerId: 113,
    salesRep: "pjackson",
    appId: 311,
    firstName: "Simon",
    lastName: "Kilo",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "male",
    maritalStatus: "divorced",
    dependents: 5,
    profilePicture: null,
    addressId: 113,
    sectionNumber: 23,
    lotNumber: 23,
    suburb: "Gerehu",
    street: "Vakari",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 3232323,
    customerMobile: 3232323,
    customerEmail: "skilo@mail.com",
    customerAddress: "P.O Box 123",
    bankId: 139,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Simon Kilo",
    accNumber: 12345678,
    loanId: 107,
    invoiceNumber: "12345678",
    purpose: "White goods purchase",
    amount: 1000,
    repaymentAmount: 250,
    term: 56,
    employerId: 109,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 3232323,
    employerMobile: 3232323,
    employerEmail: "skilo@mail.com.pg",
    fileNumber: "100101",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay9.zip",
    rawFileName: null,
    status: "Approved",
  },
  {
    customerId: 114,
    salesRep: "pjackson",
    appId: 312,
    firstName: "Duncan",
    lastName: "Kilo",
    dateOfBirth: "1991-05-02T14:00:00.000Z",
    sex: "male",
    maritalStatus: "single",
    dependents: 3,
    profilePicture: null,
    addressId: 114,
    sectionNumber: 34,
    lotNumber: 34,
    suburb: "Gerehu",
    street: "Niu Street",
    province: "Central",
    locale: "Port Moresby",
    customerPhone: 5252525,
    customerMobile: 72885393,
    customerEmail: "dkilo@mail.com.pg",
    customerAddress: "P.O Box 123",
    bankId: 140,
    bankname: "BSP",
    branch: "Waigani",
    accType: "Cheque",
    accName: "Duncan Kilo",
    accNumber: 12345678,
    loanId: 108,
    invoiceNumber: "12345678",
    purpose: "Hire Purchase",
    amount: 500,
    repaymentAmount: 50,
    term: 52,
    employerId: 110,
    employerName: "Finance Coporation Limited",
    dateOfEmployment: "2018-05-28T14:00:00.000Z",
    position: "Web Appliction Developer",
    department: "Information Technology",
    employerAddress: "P.O Box 123",
    employerPhone: 5252525,
    employerMobile: 5252525,
    employerEmail: "dkilo@mail.com.pg",
    fileNumber: "1000102",
    payMaster: "Gabriel Kanamon",
    fileName: "gdorke_essay.zip",
    rawFileName: null,
    status: "Declined",
  },
];

export const ClientRows = [
  { id: 1, name: "John Doe", company: "Brian Bell", status: "Active" },
  { id: 2, name: "John Doe", company: "Brian Bell", status: "Active" },
  { id: 3, name: "John Doe", company: "Brian Bell", status: "Active" },
  { id: 4, name: "John Doe", company: "Brian Bell", status: "Active" },
  { id: 5, name: "John Doe", company: "Brian Bell", status: "Active" },
];

export const laonHistory = [
  {
    id: 1,
    amount: 500,
    dateLodged: "2020-05-22",
    repaymentAmount: 50.5,
    comment: "",
    statusId: "Approved",
    term: 28,
    loanAmount: 500,
  },
  {
    id: 2,
    amount: 500,
    dateLodged: "2020-05-22",
    repaymentAmount: 50.5,
    comment: "",
    statusId: "Approved",
    term: 28,
    loanAmount: 500,
  },
  {
    id: 3,
    amount: 500,
    dateLodged: "2020-05-22",
    repaymentAmount: 50.5,
    comment: "Documents not provided",
    statusId: "Declined",
    term: 28,
    loanAmount: 500,
  },
  {
    id: 4,
    amount: 500,
    dateLodged: "2020-05-22",
    repaymentAmount: 50.5,
    comment: "",
    statusId: "Approved",
    term: 28,
    loanAmount: 500,
  },
];

//fake applications by users
export const fakeApplicationsByUser = {
  applications: [
    {
      dateLodged: "2021-07-13T22:40:56.000Z",
      lodgedBy: "BBStaff",
      loanAmount: 5000,
      repaymentAmount: 250,
      term: 52,
      partner: {
        name: "BrianBell",
      },
      client: {
        Id: 108,
        firstName: "Peter",
        lastName: "Totono",
        role: {
          role: "client",
        },
      },
    },
    {
      dateLodged: "2021-07-13T22:45:09.000Z",
      lodgedBy: "BBStaff",
      loanAmount: 600,
      repaymentAmount: 61,
      term: 12345678,
      partner: {
        name: "BrianBell",
      },
      client: {
        Id: 109,
        firstName: "Peniel",
        lastName: "Kalamin",
        role: {
          role: "client",
        },
      },
    },
    {
      dateLodged: "2021-07-13T22:49:49.000Z",
      lodgedBy: "BBStaff",
      loanAmount: 500,
      repaymentAmount: 60,
      term: 102,
      partner: {
        name: "BrianBell",
      },
      client: {
        Id: 110,
        firstName: "Duncan",
        lastName: "Allan",
        role: {
          role: "client",
        },
      },
    },
    {
      dateLodged: "2021-07-13T22:52:46.000Z",
      lodgedBy: "BBStaff",
      loanAmount: 10000,
      repaymentAmount: 250,
      term: 109,
      partner: {
        name: "BrianBell",
      },
      client: {
        Id: 111,
        firstName: "Kimbarely",
        lastName: "Kilo",
        role: {
          role: "client",
        },
      },
    },
    {
      dateLodged: "2021-07-14T00:55:10.000Z",
      lodgedBy: "BBStaff",
      loanAmount: 500,
      repaymentAmount: 150,
      term: 52,
      partner: {
        name: "BrianBell",
      },
      client: {
        Id: 112,
        firstName: "Simon",
        lastName: "Jones",
        role: {
          role: "client",
        },
      },
    },
  ],
};

//fake data
const createData = (
  id,
  name,
  date,
  shipTo,
  paymentMethod,
  salesRep,
  amount
) => {
  return { id, name, date, shipTo, paymentMethod, salesRep, amount };
};

export const rows = [
  createData(
    0,
    "Elvis Presley",
    "16 Mar, 2019",
    "Brian Bell",
    "Gordons",
    "Will Smith",
    312.44
  ),
  createData(
    1,
    "Paul McCartney",
    "16 Mar, 2019",
    "Brian Bell, Home Centers",
    "Boroko",
    "Will Smith",
    866.99
  ),
  createData(
    2,
    "Tom Scholz",
    "16 Mar, 2019",
    "Brian Bell",
    "Lae",
    "Will Smith",
    100.81
  ),
];

// fake user list
export const userList = [
  { id: 1, name: "John", access: "HRA" },
  { id: 2, name: "Jane", access: "AMD" },
  { id: 3, name: "Christopher", access: "OSG" },
  { id: 4, name: "Sandra", access: "Credit" },
  { id: 6, name: "Jackson", access: "BPD" },
  { id: 7, name: "John", access: "HRA" },
  { id: 8, name: "John", access: "HRA" },
];
